export const anatomy = {
  parts: {
    balance: 'cnc-token-input__balance',
    field: 'cnc-token-input__field',
    label: 'cnc-token-input__label',
    max: 'cnc-token-input__max',
    meta: 'cnc-token-input__meta',
    root: 'cnc-token-input',
    row: 'cnc-token-input__row',
    token: 'cnc-token-input__token',
    usdValue: 'cnc-token-input__usd-value',
  },
  states: {
    balance: 'data-state',
    disabled: 'data-disabled',
    interactive: 'data-interactive',
    invalid: 'data-invalid',
  },
} as const

export const dialogAnatomy = {
  parts: {
    backdrop: 'cnc-token-select-dialog__backdrop',
    close: 'cnc-token-select-dialog__close',
    content: 'cnc-token-select-dialog',
    empty: 'cnc-token-select-dialog__empty',
    favorite: 'cnc-token-select-dialog__favorite',
    favoriteLogo: 'cnc-token-select-dialog__favorite-logo',
    favorites: 'cnc-token-select-dialog__favorites',
    favoriteSymbol: 'cnc-token-select-dialog__favorite-symbol',
    header: 'cnc-token-select-dialog__header',
    list: 'cnc-token-select-dialog__list',
    positioner: 'cnc-token-select-dialog__positioner',
    row: 'cnc-token-select-dialog__row',
    rowBalance: 'cnc-token-select-dialog__row-balance',
    rowFigures: 'cnc-token-select-dialog__row-figures',
    rowLocked: 'cnc-token-select-dialog__row-locked',
    rowLogo: 'cnc-token-select-dialog__row-logo',
    rowName: 'cnc-token-select-dialog__row-name',
    rows: 'cnc-token-select-dialog__rows',
    rowSymbol: 'cnc-token-select-dialog__row-symbol',
    rowText: 'cnc-token-select-dialog__row-text',
    search: 'cnc-token-select-dialog__search',
    searchField: 'cnc-token-select-dialog__search-field',
    searchIcon: 'cnc-token-select-dialog__search-icon',
    sizer: 'cnc-token-select-dialog__sizer',
    status: 'cnc-token-select-dialog__status',
    title: 'cnc-token-select-dialog__title',
  },
} as const
